### ISSUE TITLE
Initial release TODO

### ISSUE THREAD

**Issue by nightlark** [LLNL/cyme-launcher#3]
https://software.llnl.gov/about/faq/#my-project-is-approved-for-release-now-what

- [x] Add license and release number
- [x] Add README file
- [x] Add NOTICE file
- [x] Add CODE OF CONDUCT file
- [x] Add CONTRIBUTING file
- [ ] Add some user documentation (RtD later?)
- [ ] Tag initial version with release notes
- [ ] Submit repo to [DOE CODE](https://www.osti.gov/doecode/faq#what-is)
- [ ] Add DOI

**Comment by nightlark** [comment]
DOI: 10.11578/dc.20220822.2

DOE CODE ID: 80061, https://doi.org/10.11578/dc.20220822.2
